### ISSUE TITLE
Groupmanagement - Removing users from group

### ISSUE THREAD

**Issue by GriffinSauce** [GriffinSauce/Grouplanner#55]
Tap face -> red overlay with X -> tap to remove ->  dialog "are you sure"

**Comment by HalleyInteractive** [comment]
Only if you have the *power* I assume. Would this be the group creator? Or is this part of the 'Change settings' right that we still need to implement?

**Comment by GriffinSauce** [comment]
Yes, will eventually be part of the permissions but for now it can be implemented generally (anyone can do it). When permissions are implemented we can do a API-side check to see whether you are allowed to.

**Comment by HalleyInteractive** [comment]
API Function for removing a member from the group is implemented, see #56.
'''delete/group/member'''
