### ISSUE TITLE
Groupmanagement - Removing a group

### ISSUE THREAD

**Issue by GriffinSauce** [GriffinSauce/Grouplanner#56]

**Comment by HalleyInteractive** [comment]
I think that practically this will unsubscribe you from the group as a user. So the group can continue for all other users.

When the last user unsubscribes we should remove the group from the database. Or leave it there for evah.

We should also check what needs to happen if the group admin unsubscribes from the group. Maybe he can point the new group leader.

**Comment by GriffinSauce** [comment]
Agreed, so the action should be called "Leave group".

When the last leaves tell them "If you leave this group all data will be destroyed, are you sure?" They are just planned dates + notes after all. If it;s a big deal to keep them, don't leave the group. :)

At this moment the admin does not have any rights above others. But yes, appointing a new admin seems like the way to go. (put that user's ID in the group.creator property, done).
