### ISSUE TITLE
Add a group overview page

### ISSUE THREAD

**Issue by HalleyInteractive** [GriffinSauce/Grouplanner#79]
Instead of making a group settings page we could make an overview or info page. This would show some genal data like group creation date, dates planned and a group management section.

In this management section we can add the option to remove members.

**Comment by GriffinSauce** [comment]
Yes agreed. This is a nice place for stats in the future.

**Comment by HalleyInteractive** [comment]
We can expand the group management tab if we need to display more info on the group. Closing this issue for now.
