### ISSUE TITLE
Store group updates

### ISSUE THREAD

**Issue by HalleyInteractive** [GriffinSauce/Grouplanner#91]
We should store the following updates of a group:
- User invited to group
- User joined group
- User left group
- User planned dates (When says he's done entering dates)
- Date planned for period

**Comment by GriffinSauce** [comment]
Forever? How long will this log be?

Perhaps we can create a database worker that periodically cuts logs down to size.

**Comment by HalleyInteractive** [comment]
I've added a events property to the group schema (group-updates branch), We can store all group events in here. 

We could store the last 100 events in there, and maybe only return 25 by default to the interface.

We can add a cron job to remove all events above the 100 limit, and at the same time store the count for this event somewhere in the group data.
